# -*- coding: utf-8 -*-
"""ComsThread.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V9cwTmUujT2uFVf_oKZ-_wnhlb_fEjL7
"""

from threading import Thread
import time

class ComsThread(Thread):
    def __init__(self):
      super().__init__()
      self.para=0
    def run(self):
        while(1):
          time.sleep(1)
          self.para=self.para+1
    def call(self):
      return self.para

if __name__ == "__main__":
    agent = ComsThread()
    print(agent.call())

agent.start()

print(agent.call())

